

export default {
    //AUTH
    AUTH_STACK: 'AUTH_STACK',
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_SIGN_UP: 'AUTH_SIGN_UP',

    //USER
    USER_STACK: 'USER_STACK',
    USER_PROFILE: 'USER_PROFILE',
    USER_EDIT_PROFILE: 'USER_EDIT_PROFILE',
}
